// age-mint: browser-native age X25519 keygen (rework slice 2, civic-node#58). The oracle is the REAL
// tool: a fixture pair generated by age-keygen is embedded (so the cross-check runs everywhere), and
// when the age/age-keygen binaries are present the test also round-trips LIVE — our minted recipient
// must decrypt what age encrypts, and age-keygen -y must agree with recipientOf().
import { spawnSync } from "node:child_process";
import { writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  bech32Encode, bech32Decode, encodeRecipient, encodeIdentity, parseRecipient, parseIdentity,
  mintAgeIdentity, recipientOf, attestRecipient, ATTEST_SCHEMA,
} from "./age-mint.mjs";

let fails = 0;
function ok(c, m) { if (c) console.log("  ok: " + m); else { console.error("  FAIL: " + m); fails++; } }
function throws(fn, m) { try { fn(); ok(false, m); } catch { ok(true, m); } }

// 1. bech32 — BIP-173 conformance on the shapes age uses
{
  ok(bech32Decode("A12UEL5L").hrp === "a", "a BIP-173 valid vector decodes (case-folded hrp)");
  throws(() => bech32Decode("A12UeL5L"), "mixed case is refused");
  throws(() => bech32Decode("a12uel5x"), "a corrupted checksum is refused");
  throws(() => bech32Decode("1qqq"), "an empty hrp is refused");
  const rt = bech32Decode(bech32Encode("age", Uint8Array.from({ length: 32 }, (_, i) => i)));
  ok(rt.hrp === "age" && rt.bytes.length === 32 && rt.bytes[31] === 31, "encode → decode round-trips 32 bytes");
}

// 2. the embedded age-keygen fixture — the offline oracle
const FIXTURE = {
  identity: "AGE-SECRET-KEY-1H48AZ5JVK9MT79N26407TJRAA6KFAWRJEDPRGLEGH57WP7HQHN3SRGZVSF",
  recipient: "age1586sf5fgqv0cxt2xgyyl4p2s6f7x4eaneg28rhkpaj4sm8e5x92qtqwy8l",
};
{
  ok(parseIdentity(FIXTURE.identity).length === 32, "a real age-keygen identity parses (hrp, checksum, 32 bytes)");
  ok(parseRecipient(FIXTURE.recipient).length === 32, "a real age-keygen recipient parses");
  ok(encodeIdentity(parseIdentity(FIXTURE.identity)) === FIXTURE.identity, "identity re-encodes byte-identical (uppercase)");
  ok(encodeRecipient(parseRecipient(FIXTURE.recipient)) === FIXTURE.recipient, "recipient re-encodes byte-identical (lowercase)");
  const derived = await recipientOf(FIXTURE.identity);
  ok(derived === FIXTURE.recipient, "recipientOf() re-derives the REAL tool's recipient — WebCrypto agrees with age-keygen -y");
  throws(() => parseRecipient(FIXTURE.identity), "an identity is not a recipient (hrp check)");
  throws(() => parseIdentity(FIXTURE.recipient.toUpperCase()), "a recipient is not an identity (hrp check)");
}

// 3. minting — fresh, self-consistent, unique
{
  const a = await mintAgeIdentity();
  const b = await mintAgeIdentity();
  ok(/^AGE-SECRET-KEY-1[A-Z0-9]+$/.test(a.identity), "minted identity wears the age secret-key format");
  ok(/^age1[a-z0-9]+$/.test(a.recipient), "minted recipient wears the age recipient format");
  ok(a.recipient.length === FIXTURE.recipient.length && a.identity.length === FIXTURE.identity.length,
     "minted strings are the exact lengths the real tool emits");
  ok((await recipientOf(a.identity)) === a.recipient, "the minted pair is self-consistent (derive == exported)");
  ok(a.identity !== b.identity && a.recipient !== b.recipient, "two mints are two keys");
}

// 4. live cross-check with the real binaries, when present (the strongest oracle: true interop)
{
  const probe = spawnSync("age-keygen", ["--version"], { encoding: "utf8" });
  if (probe.error) {
    console.log("  (skip: age-keygen not on PATH — live interop check skipped; the embedded fixture covered the oracle)");
  } else {
    const dir = mkdtempSync(join(tmpdir(), "age-mint-"));
    try {
      const m = await mintAgeIdentity();
      const idFile = join(dir, "id.txt");
      writeFileSync(idFile, m.identity + "\n");
      const y = spawnSync("age-keygen", ["-y", idFile], { encoding: "utf8" });
      ok(y.stdout.trim() === m.recipient, "age-keygen -y agrees with our minted recipient");
      const enc = spawnSync("age", ["-r", m.recipient], { input: "the tank opens\n" });
      const dec = spawnSync("age", ["-d", "-i", idFile], { input: enc.stdout, encoding: "utf8" });
      ok(dec.stdout === "the tank opens\n", "age encrypts to our recipient and our identity decrypts it — true interop");
    } finally { rmSync(dir, { recursive: true, force: true }); }
  }
}

// 5. gesture-gated export provenance — the object shape, with the gate injected (the gate itself is
// gesture.test.mjs's to prove)
{
  let gated = null;
  const gate = async (obj, identity, cred) => { gated = { obj, identity, cred }; return { signed: { ...obj, sig: "s" }, gesture: {} }; };
  const out = await attestRecipient(FIXTURE.recipient, "ID", "CRED", { gate, at: "2026-07-03T00:00:00Z" });
  ok(gated && gated.obj.schema === ATTEST_SCHEMA && gated.obj.recipient === FIXTURE.recipient && gated.obj.at === "2026-07-03T00:00:00Z",
     "attestRecipient hands the gate the schema'd artifact (recipient + injectable at)");
  ok(gated.identity === "ID" && gated.cred === "CRED" && out.signed.sig === "s", "identity/cred pass through; the gated result returns");
  ok(!JSON.stringify(gated.obj).includes("SECRET-KEY"), "the artifact carries the recipient only — never an identity");
  let threw = false;
  try { await attestRecipient("age1notachecksum", "ID", "CRED", { gate }); } catch { threw = true; }
  ok(threw, "a malformed recipient is refused before any gesture is asked for");
}

if (fails) { console.error(`\n${fails} FAILED`); process.exit(1); }
console.log("\nall age-mint tests passed");
